# Étape 1: Construction avec Maven
FROM maven:3.9-eclipse-temurin-21 AS builder
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

# Étape 2: Exécution  
FROM eclipse-temurin:21-jdk
WORKDIR /app
COPY --from=builder /app/target/countryService-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8082
CMD ["java", "-jar", "app.jar"]
